all: rshell.h rshell.cpp
	g++ -Wall -Werror -ansi -pedantic -o rshell rshell.cpp; mv rshell /home/csmajs/wrahi001/rshell/bin
rshell: rshell.h rshell.cpp
	g++ -Wall -Werror -ansi -pedantic -o rshell  rshell.cpp; mv rshell /home/csmajs/wrahi001/rshell/bin
