all:
	g++ -Wall -Werror -ansi -pedantic -o rshell rshell.cpp; cp rshell /home/csmajs/wrahi001/rshell/bin
rshell:
	g++ -Wall -Werror -ansi -pedantic -o rshell  rshell.cpp; cp rshell /home/csmajs/wrahi001/rshell/bin
